assembly_linkage.o: assembly_linkage.S assembly_linkage.h
boot.o: boot.S multiboot.h x86_desc.h types.h int_handlers.h
x86_desc.o: x86_desc.S x86_desc.h types.h int_handlers.h
i8259.o: i8259.c i8259.h types.h lib.h
int_handlers.o: int_handlers.c int_handlers.h types.h lib.h i8259.h rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h int_handlers.h lib.h \
 i8259.h rtc.h debug.h paging.h assembly_linkage.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h lib.h
rtc.o: rtc.c rtc.h lib.h types.h
