assembly_linkage.o: assembly_linkage.S assembly_linkage.h x86_desc.h \
  types.h int_handlers.h
boot.o: boot.S multiboot.h x86_desc.h types.h int_handlers.h
x86_desc.o: x86_desc.S x86_desc.h types.h int_handlers.h
dir.o: dir.c dir.h
file_array.o: file_array.c file_array.h assembly_linkage.h types.h lib.h \
  int_handlers.h i8259.h terminal.h paging.h file_system.h x86_desc.h \
  rtc.h
file_system.o: file_system.c file_system.h types.h lib.h terminal.h
i8259.o: i8259.c i8259.h types.h lib.h
int_handlers.o: int_handlers.c int_handlers.h types.h lib.h i8259.h \
  terminal.h rtc.h file_array.h assembly_linkage.h paging.h file_system.h \
  x86_desc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h int_handlers.h lib.h \
  i8259.h terminal.h rtc.h debug.h paging.h assembly_linkage.h \
  file_array.h file_system.h sys_calls.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h lib.h
rtc.o: rtc.c rtc.h lib.h types.h int_handlers.h i8259.h terminal.h
sys_calls.o: sys_calls.c sys_calls.h types.h lib.h x86_desc.h \
  int_handlers.h i8259.h terminal.h
terminal.o: terminal.c terminal.h lib.h types.h
